### ISSUE TITLE
[feedback] perhaps swap the register and constant names.

### ISSUE THREAD

**Issue by nww02** [rotoclone/strategic-communication#3]
in business speak I tend to find they align a THING with a PRACTICE, rather than a PRACTICE with a THING, 

so 

align marketing with best practice

tends to make more 'sense' (if you can loosely use that word for business bullcrap), than

align best practice with marketing 

:)

**Comment by rotoclone** [comment]
I'm not sure it makes sense to swap them in every context, but I agree that having the constants go first in assignment operations reads better.

**Comment by nww02** [comment]
I like it!    The aligns look quite natural now hehe

align Sales and Legal with customer experience
align Engineering and Marketing with revenue streams
align Engineering, HR and Engineering with core competencies
align Sales with best practices
produce customer experience
deliver core competencies
align stakeholder engagement with core competencies
integrate core competencies and best practices
produce core competencies
deliver core competencies
align core competencies with key performance indicators
backburner best practices
integrate core competencies and best practices
produce core competencies
align PR and legal with assets
produce assets
integrate customer experience with revenue streams
deliver customer experience
deliver core competencies
integrate core competencies and best practices
deliver core competencies
deliver key performance indicators
optimize stakeholder engagement
deliver stakeholder engagement
