### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by dnchu** [rotoclone/strategic-communication#5]
I made a syntax highlighter for VS Code

https://github.com/dnchu/vscode-strategic-communication

**Comment by tannerntannern** [comment]
Holy crap @dnchu you are the best!

**Comment by rotoclone** [comment]
I love it. Added a link to the readme: https://github.com/rotoclone/strategic-communication/commit/d1a8e21df372bbcc32c2ccad3f2ebd43f3311279
